services:
    postgres:
        container_name: mangarider_db
        image: postgres:latest
        environment:
            POSTGRES_USER: sa
            POSTGRES_PASSWORD: password
            PG_DATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - '5432:5432'
        networks:
            - postgres-network
        restart: unless-stopped
networks:
    postgres-network:
        driver: bridge
volumes:
    postgres: