server:
  port: ${APPLICATION_PORT:8080}
spring:
  application:
    name: MangaRiderBackend
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/service_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: create-drop

security:
  basic-prefix: 'Basic '
  jwt-prefix: 'Bearer '
  role-key: 'role'
  issuer: 'manga-reader'
  secret-key: '722236765770276c3c21344b6a455f3662447d3b4b7b3e2c2b707d7e3e'
  token-live-time: 1800000

