server:
  port: ${APPLICATION_PORT:8080}
spring:
  application:
    name: MangaRiderBackend
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/service_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  basic-prefix: 'Basic '
  jwt-prefix: 'Bearer '
  role-key: 'role'
  issuer: 'manga-reader'
  secret-key: '722236765770276c3c21344b6a455f3662447d3b4b7b3e2c2b707d7e3e'
  token-live-time: 1800000

aws:
  access:
    key: ${AWS_ACCESS_KEY}
  secret:
    key: ${AWS_SECRET_KEY}
  s3:
    bucket: ${AWS_BUCKET}
    region: ${AWS_REGION}

image:
  supported-mime-types:
    - "image/gif"
    - "image/png"
    - "image/jpeg"
  user-folder: 'USER/%s/PROFILE/%s'
  #                 userId      file
  manga-folder: 'USER/%s/MANGA/%s/%s'
  #                 userId   mangaID file
  regex: ([0-9]|[A-Z]|[a-z]|[!\-_.*'\(\)])+
