server:
  port: ${APPLICATION_PORT:8080}
spring:
  application:
    name: MangaRiderBackend
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/service_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: create-drop

